### ISSUE TITLE
Add CI/CD workflow and issues template

### ISSUE THREAD

**Issue by TheAwiteb** [TheAwiteb/impl_new#1]
## Description
Add a CI/CD workflow and issues template, this will help contributors to know what to do and how to do it.

## Tasks
- [x] Bug report template
- [x] Feature request template
- [x] question template
---
- [x] Rustfmt
- [x] Clippy
- [x] Tests
---
- [x] Add a CI/CD badge to the README.md
---
- [x] Publish to crates.io for tags
